from pathlib import Path

from setuptools import find_packages, setup

package_name = "manus_bridge"
package_root = Path(__file__).resolve().parent

# `rawviz` is generated by build.sh, which links it against the vendored Manus
# SDK. It is installed as executable data only once it exists, so a checkout
# whose SDK is still a Git LFS pointer still builds the workspace.
executables = ["rawviz"] if (package_root / "rawviz").is_file() else []
# Paths must stay relative to this file: colcon resolves data_files against the
# package directory and rejects absolute sources.
calibration = [f"calibration/{path.name}"
               for path in sorted((package_root / "calibration").glob("*.mcal"))]

data_files = [
    ("share/ament_index/resource_index/packages", ["resource/" + package_name]),
    ("share/" + package_name, ["package.xml"]),
    ("share/" + package_name + "/calibration", calibration),
    ("share/" + package_name + "/udev", ["90-manus.rules"]),
]
if executables:
    data_files.append(("share/" + package_name, executables))

setup(
    name=package_name,
    version="0.3.0",
    packages=find_packages(exclude=["tests", "tests.*"]),
    data_files=data_files,
    install_requires=["setuptools"],
    zip_safe=True,
    maintainer="Tianji operators",
    maintainer_email="ops@example.com",
    description="Manus Metaglove Pro input collector, calibration profiles and /hand_input publisher",
    license="Apache-2.0",
    entry_points={
        "console_scripts": [
            "manus_hand_input = manus_bridge.manus_hand_input:main",
        ],
    },
)
