#pragma once
#include "tianji_v131/config.hpp"
namespace tianji_v131 {
// Exact velocity control profile from qp_ik_pico_ee_v131_velocity_qp_mujoco.yaml.
// Backend kinematics/bounds use the original fast model; host Home is unchanged.
inline QpIkConfig originalVelocityProfile() {
  QpIkConfig c;
  c.controller.rate_hz = 200.0;
  c.controller.model_state_only = true;
  c.ik_algorithm = IkAlgorithm::kPicoEeV131VelocityQp;
  c.cartesian_servo.kp_position << 15.0, 15.0, 15.0;
  c.cartesian_servo.kp_orientation << 10.0, 10.0, 10.0;
  c.cartesian_servo.adaptive_gain_enabled = true;
  c.cartesian_servo.kp_position_near << 4.0, 4.0, 4.0;
  c.cartesian_servo.kp_orientation_near << 3.0, 3.0, 3.0;
  c.cartesian_servo.position_gain_transition_start_m = 0.02;
  c.cartesian_servo.position_gain_transition_end_m = 0.22;
  c.cartesian_servo.orientation_gain_transition_start_rad = 0.03;
  c.cartesian_servo.orientation_gain_transition_end_rad = 0.15;
  c.cartesian_servo.kff_linear = 0.0;
  c.cartesian_servo.kff_angular = 0.0;
  c.cartesian_servo.feedforward_filter_cutoff_hz = 5.0;
  c.cartesian_servo.prediction_horizon_seconds = 0.015;
  c.cartesian_servo.target_timeout_seconds = 0.050;
  c.cartesian_servo.max_linear_velocity = 3.0;
  c.cartesian_servo.max_angular_velocity = 12.0;
  c.cartesian_otg.enabled = true;
  c.cartesian_otg.translation_position_mode = true;
  c.cartesian_otg.translation_tracking_enabled = true;
  c.cartesian_otg.translation_tracking_gain = 30.0;
  c.cartesian_otg.translation_stationary_velocity_threshold = 1.0e-4;
  c.cartesian_otg.translation_prediction_enabled = true;
  c.cartesian_otg.translation_prediction_horizon_seconds = 0.015;
  c.cartesian_otg.stationary_hold_enabled = true;
  c.cartesian_otg.stationary_hold_dwell_seconds = 0.15;
  c.cartesian_otg.translation_hold_enter_velocity_m_s = 0.06;
  c.cartesian_otg.translation_hold_exit_velocity_m_s = 0.12;
  c.cartesian_otg.translation_hold_exit_position_error_m = 0.020;
  c.cartesian_otg.orientation_hold_enter_velocity_rad_s = 0.12;
  c.cartesian_otg.orientation_hold_exit_velocity_rad_s = 0.25;
  c.cartesian_otg.orientation_hold_exit_error_rad = 0.035;
  c.cartesian_otg.translation_velocity_max = 3.0;
  c.cartesian_otg.translation_acceleration_max = 30.0;
  c.cartesian_otg.translation_jerk_max = 1000.0;
  c.cartesian_otg.angular_velocity_max = 12.0;
  c.cartesian_otg.angular_acceleration_max = 100.0;
  c.cartesian_otg.angular_jerk_max = 3000.0;
  c.cartesian_otg.orientation_gain = 10.0;
  c.cartesian_otg.orientation_settle_error_rad = 1.0e-5;
  c.cartesian_otg.angular_settle_velocity_rad_s = 1.0e-4;
  c.cartesian_otg.angular_settle_acceleration_rad_s2 = 1.0e-3;
  c.pico_ee_v131_velocity_qp.enabled = true;
  c.pico_ee_v131_velocity_qp.zero_posture_left << 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0;
  c.pico_ee_v131_velocity_qp.zero_posture_right << 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0;
  c.pico_ee_v131_velocity_qp.posture_time_constant_seconds = 2.5;
  c.pico_ee_v131_velocity_qp.velocity_regularization_weight = 1.0e-4;
  c.pico_ee_v131_velocity_qp.continuity_weight = 1.0e-3;
  c.pico_ee_v131_velocity_qp.jerk_trend_weight = 2.0e-2;
  c.pico_ee_v131_velocity_qp.posture_weight = 8.0e-3;
  c.pico_ee_v131_velocity_qp.wrist_posture_weight_scale = 1.0;
  c.pico_ee_v131_velocity_qp.slack_weight_position = 3.0e4;
  c.pico_ee_v131_velocity_qp.slack_weight_orientation = 3.0e4;
  c.pico_ee_v131_velocity_qp.slack_position_scale = 3.0;
  c.pico_ee_v131_velocity_qp.slack_orientation_scale = 12.0;
  c.pico_ee_v131_velocity_qp.task_scaling_min_position = 0.75;
  c.pico_ee_v131_velocity_qp.task_scaling_min_orientation = 0.75;
  c.pico_ee_v131_velocity_qp.task_scaling_weight_position = 8000.0;
  c.pico_ee_v131_velocity_qp.task_scaling_weight_orientation = 3000.0;
  c.pico_ee_v131_velocity_qp.equality_tolerance = 1.0e-8;
  c.pico_ee_v131_velocity_qp.singular_value_threshold = 0.05;
  c.pico_ee_v131_velocity_qp.singularity_critical_threshold = 0.015;
  c.pico_ee_v131_velocity_qp.singularity_orientation_scale = 0.15;
  c.pico_ee_v131_velocity_qp.singularity_posture_multiplier = 8.0;
  c.pico_ee_v131_velocity_qp.singularity_velocity_multiplier = 4.0;
  c.pico_ee_v131_velocity_qp.finite_difference_rad = 1.0e-4;
  c.pico_ee_v131_velocity_qp.singularity_escape_speed_rad_s = 0.15;
  c.pico_ee_v131_velocity_qp.singularity_escape_weight = 0.03;
  c.pico_ee_v131_velocity_qp.gradient_update_rate_hz = 50.0;
  c.pico_ee_v131_velocity_qp.gradient_max_age_seconds = 0.04;
  c.pico_ee_v131_velocity_qp.warm_start_reset_threshold_rad = 0.05;
  c.pico_ee_v131_velocity_qp.remove_dexhand_speed_box = true;
  c.pico_ee_v131_velocity_qp.remove_dexhand_cartesian_caps = true;
  c.pico_ee_v131_velocity_qp.temporal_envelope.enabled = true;
  c.pico_ee_v131_velocity_qp.temporal_envelope.max_acceleration_rad_s2 << 60.0, 60.0, 60.0, 90.0, 90.0, 90.0, 90.0;
  c.pico_ee_v131_velocity_qp.temporal_envelope.max_jerk_rad_s3 << 3000.0, 3000.0, 3000.0, 4500.0, 4500.0, 4500.0, 4500.0;
  c.pico_ee_v131_velocity_qp.temporal_envelope.conflict_policy = FullJointTemporalEnvelopeConflictPolicy::kRelaxToSafety;
  c.hierarchical_qp.lambda_reg = 1.0e-4;
  c.hierarchical_qp.posture_weight = 1.0e-3;
  c.hierarchical_qp.wrist_posture_weight_scale = 1.0;
  c.hierarchical_qp.continuity_weight = 1.0e-3;
  c.hierarchical_qp.jerk_weight = 0.0;
  c.hierarchical_qp.nominal_gain = 0.2;
  c.hierarchical_qp.arm_angle_weight = 0.0;
  c.hierarchical_qp.task_scaling_enabled = true;
  c.hierarchical_qp.task_scaling_min_position = 0.75;
  c.hierarchical_qp.task_scaling_min_orientation = 0.75;
  c.hierarchical_qp.task_scaling_weight_position = 8000.0;
  c.hierarchical_qp.task_scaling_weight_orientation = 3000.0;
  c.hierarchical_qp.slack_weight_position = 1.0e4;
  c.hierarchical_qp.slack_weight_orientation = 3.0e3;
  c.hierarchical_qp.slack_position_scale = 1.0;
  c.hierarchical_qp.slack_orientation_scale = 1.0;
  c.hierarchical_qp.equality_tolerance = 1.0e-8;
  c.joint_limits.margin_rad = 0.05;
  c.joint_limits.velocity_scale = 1.0;
  c.joint_limits.max_acceleration_rad_s2 << 60.0, 60.0, 60.0, 90.0, 90.0, 90.0, 90.0;
  c.joint_limits.braking_acceleration_rad_s2 << 45.0, 45.0, 45.0, 67.5, 67.5, 67.5, 67.5;
  c.joint_limits.hard_jerk_enabled = true;
  c.joint_limits.max_jerk_rad_s3 << 3000.0, 3000.0, 3000.0, 4500.0, 4500.0, 4500.0, 4500.0;
  c.qpoases.max_working_set_recalculations = 50;
  c.qpoases.cpu_time_limit_seconds = 0.0005;
  c.safety.bound_tolerance = 1.0e-8;
  c.safety.hessian_eigenvalue_tolerance = 1.0e-10;
  c.safety.max_target_position_step = 0.05;
  c.safety.max_target_orientation_step = 0.20;
  return c;
}
} // namespace tianji_v131
